controller:
  image:
    repository: jenkins/jenkins
    tag: "lts"
    pullPolicy: Always

  # CORRECT: Modern admin configuration format
  admin:
    username: admin
    password: admin123

  # Use specific plugin versions for stability
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - prometheus:latest

  # Container security context
  containerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false

  # Pod security context
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  # Init container security context
  initContainerSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false

  # Service account
  serviceAccount:
    create: true
    name: jenkins

  # Service type for EKS
  serviceType: ClusterIP

  # Enable persistence and use the default EBS StorageClass for EKS
  persistence:
    enabled: true
    storageClass: gp3 # Or "gp3" if your EKS cluster supports it
    size: 10Gi
    annotations: {}

  # Resources
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"

  # Executors
  numExecutors: 2

# Disable agent
agent:
  enabled: false

# RBAC
rbac:
  create: true
  readSecrets: false
