version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: dungeon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dungeon
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    restart: always

  k6:
    image: grafana/k6
    volumes:
      - ./stress/test.js:/scripts/test.js
    depends_on:
      - app
    entrypoint: ["k6", "run", "/scripts/test.js"]

volumes:
  pgdata:
