version: "3.9"

services:
  library:
    build:
      context: ./library
      dockerfile: Dockerfile
    container_name: library
    ports:
      - "8080:8080"
    networks:
      - graphql-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  radio:
    build:
      context: ./radio
      dockerfile: Dockerfile
    container_name: radio
    ports:
      - "8000:8000"
    networks:
      - graphql-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  apollo:
    build:
      context: ./apollo
      dockerfile: Dockerfile
    container_name: apollo-gateway
    ports:
      - "4000:4000"
    depends_on:
      library:
        condition: service_healthy
      radio:
        condition: service_healthy
    environment:
      LIBRARY_URL: "http://library:8080/graphql"
      RADIO_URL: "http://radio:8000/graphql"
    networks:
      - graphql-network

networks:
  graphql-network:
    driver: bridge
