services:

  postgres:
    image: postgres:16-alpine
    container_name: users-postgres
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: users-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/usersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      ENCRYPTION_SECRET_KEY: "D22/hPaZir4ig/SR295dQSMhi6NxWALWitBpliSR5ks="
      ENCRYPTION_HMAC_KEY: "Ktl1AckqC3taKMlPIXv5yDrEZOBOvgB6OK+ppEQ8mHQ="
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: