# Generated by Django 5.2.8 on 2025-12-02 21:28

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pub_type', models.CharField(choices=[('pub', 'Pub'), ('bar', 'Bar'), ('brewery', 'Brewery'), ('cocktail_bar', 'Cocktail Bar'), ('wine_bar', 'Wine Bar')], default='pub', max_length=20)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['location'], name='pubs_pub_locatio_f6c17a_idx'), models.Index(fields=['pub_type'], name='pubs_pub_pub_typ_e2d629_idx')],
            },
        ),
    ]
