version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: booklist
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  opensearch:
    image: opensearchproject/opensearch:2.17.1
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
      - "9600:9600"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    # Remove the bind mount for production/stable builds
    # volumes:
    #   - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - opensearch
    environment:
      DATABASE_URL: postgres://django:django@db:5432/booklist
      ELASTICSEARCH_DSL_HOSTS: http://opensearch:9200

volumes:
  postgres_data:
